lseq <- function(from, to, length.out ) exp(seq(log(from), log(to), length.out = length.out))

# monarchs
parmfile_monarch <- rbind(data.frame(filter_facet = "pop", # maf
                                     analysis_facet = "pop",
                                     chr = "group",
                                     maf = seq(0, .1, by = .01),
                                     mac = 0,
                                     hwe = 1e-6,
                                     hwe_facet = "pop",
                                     min_ind = .5,
                                     min_loci = .5,
                                     seed = 12342,
                                     par = FALSE,
                                     step = 100,
                                     sigma = 50),
                          data.frame(filter_facet = "pop", # mac
                                     analysis_facet = "pop",
                                     chr = "group",
                                     maf = FALSE,
                                     mac = 1:5,
                                     hwe = 1e-6,
                                     hwe_facet = "pop",
                                     min_ind = .5,
                                     min_loci = .5,
                                     seed = 12342,
                                     par = FALSE,
                                     step = 100,
                                     sigma = 50),
                          data.frame(filter_facet = "pop", # hwe
                                     analysis_facet = "pop",
                                     chr = "group",
                                     maf = FALSE,
                                     mac = 1,
                                     hwe = lseq(1e-6, .05, 10),
                                     hwe_facet = "pop",
                                     min_ind = .5,
                                     min_loci = .5,
                                     seed = 12342,
                                     par = FALSE,
                                     step = 100,
                                     sigma = 50),
                          data.frame(filter_facet = "pop", # missingness
                                     analysis_facet = "pop",
                                     chr = "group",
                                     maf = FALSE,
                                     mac = 1,
                                     hwe = 1e-6,
                                     hwe_facet = "pop",
                                     min_ind = seq(.5, .9, length.out = 10)[-1],
                                     min_loci = seq(.5, .9, length.out = 10)[-1],
                                     seed = 12342,
                                     par = FALSE,
                                     step = 100,
                                     sigma = 50))

data.table::fwrite(parmfile_monarch, "monarch_filt_parmfile.txt", 
                   quote = F, sep = "\t", row.names = F, col.names = F)


# ypp
parmfile_ypp <- rbind(data.frame(filter_facet = "pop", # maf
                                 analysis_facet = "pop",
                                 chr = "CHROM",
                                 maf = seq(0, .1, by = .01),
                                 mac = 0,
                                 hwe = 1e-6,
                                 hwe_facet = "pop",
                                 min_ind = .5,
                                 min_loci = .5,
                                 seed = 12342,
                                 par = FALSE,
                                 step = 100,
                                 sigma = 50),
                      data.frame(filter_facet = "pop", # mac
                                 analysis_facet = "pop",
                                 chr = "CHROM",
                                 maf = FALSE,
                                 mac = 1:5,
                                 hwe = 1e-6,
                                 hwe_facet = "pop",
                                 min_ind = .5,
                                 min_loci = .5,
                                 seed = 12342,
                                 par = FALSE,
                                 step = 100,
                                 sigma = 50),
                      data.frame(filter_facet = "pop", # hwe
                                 analysis_facet = "pop",
                                 chr = "CHROM",
                                 maf = FALSE,
                                 mac = 1,
                                 hwe = lseq(1e-6, .05, 10),
                                 hwe_facet = "pop",
                                 min_ind = .5,
                                 min_loci = .5,
                                 seed = 12342,
                                 par = FALSE,
                                 step = 100,
                                 sigma = 50),
                      data.frame(filter_facet = "pop", # missingness
                                 analysis_facet = "pop",
                                 chr = "CHROM",
                                 maf = FALSE,
                                 mac = 1,
                                 hwe = 1e-6,
                                 hwe_facet = "pop",
                                 min_ind = seq(.5, .9, length.out = 10)[-1],
                                 min_loci = seq(.5, .9, length.out = 10)[-1],
                                 seed = 12342,
                                 par = FALSE,
                                 step = 100,
                                 sigma = 50))

data.table::fwrite(parmfile_ypp, "ypp_filt_parmfile.txt", 
                   quote = F, sep = "\t", row.names = F, col.names = F)
